version: "3.8"

services:
  app:
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - node-modules:/app/node_modules
    command: npm run dev

volumes:
  node-modules: {}
