name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "19.0.1"

      - name: Install dependencies
        run: |
          npm ci

      - name: Lint with Eslint
        run: |
          npm run lint

      - name: Check code formatting
        run: |
          npm run format:check

      - id: semantic-release
        name: Run semantic-release
        run: |
          npx semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        if: ${{ steps.semantic-release.outputs.nextVer != null }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        if: ${{ steps.semantic-release.outputs.nextVer != null }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        if: ${{ steps.semantic-release.outputs.nextVer != null }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            yujiosaka/slack-king-of-time:${{ steps.semantic-release.outputs.nextVer }}
            yujiosaka/slack-king-of-time:latest
        if: ${{ steps.semantic-release.outputs.nextVer != null }}
